# -*- mode: toml; -*-
[profile.default]
allow_paths = ['interfaces', 'contracts', 'src']
auto_detect_solc = true
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 1
block_timestamp = 1
broadcast = 'broadcast'
cache = true
cache_path = 'cache'

# includes the contract's metadata in the contract's json artifact
extra_output = ['irOptimized', 'evm.assembly']
# emits the output selection as separate json artifact files
extra_output_files = ['metadata']

ffi = true
force = false

# This is an Option, so we can determine in fork mode whether to use the config's gas price
# (if set by user) or the remote client's gas price Option<u64>
gas_price = 10
gas_limit = 9223372036854775807
block_base_fee_per_gas = 0
gas_reports = ['*']
evm_version = 'london'

# Ignored Error codes
# 2018 Function state mutability can be restricted to pure
# 3420 Source file does not specify required compiler version
# 3716 Multiple SPDX license identifiers found in source file
ignored_error_codes = [
	1878,
	2018,
	3420,
	3716,
]

initial_balance = '0xffffffffffffffffffffffff'
sender = '0xafFEaFFEAFfeAfFEAffeaFfEAfFEaffeafFeAFfE'
tx_origin = '0xAaaaAaAAaaaAAaAAaAaaaaAAAAAaAaaaAaAaaAA0'
memory_limit = 33_554_432
names = false
no_storage_caching = false
offline = false

# repo layout
# src = 'contracts'
# test = 'contracts/test'
src = 'src'
test = 'test'
script = 'script'
out = 'out'
libraries = []
libs = [
	'lib',
	'node_modules',
]
remappings = [
	'ds-test/=lib/ds-test/src/',
	'forge-std/=lib/forge-std/src/',
	'prb-test/=lib/prb-test/src/',
	'solmate/=lib/solmate/src/',
	'test-utils/=lib/test-utils/src/',
	'@prb/test/=node_modules/@prb/test/src/',
]

# compiler settings
build_info = false
verbosity = 2
via_ir = true
# revert_strings = "verboseDebug"
revert_strings = "debug"
optimizer = true
optimizer_runs = 1_337
# this may need to be uncommented if viaIR has issues
# optimizerSteps = ''

sizes = false
bytecode_hash = 'none'
cbor_metadata = false
sparse_mode = true

fuzz_runs = 512

[[profile.default.fs_permissions]]
access = 'read'
path = 'out'

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[profile.ci]
optimizer = false
fuzz_runs = 4_069
force = true
verbosity = 4

[fuzz]
runs = 896
depth = 21
# max_test_rejects = 65_536
# max_global_rejects = 81_920
max_test_rejects = 81_920
max_local_rejects = 16_384
dictionary_weight = 80
include_storage = true
include_push_bytes = true
fail_on_revert = false
call_override = false

[invariant]
runs = 512
depth = 20
fail_on_revert = false
call_override = false
dictionary_weight = 85
include_storage = true
include_push_bytes = true

# I don't think fmt is ready yet, YMMV
# [fmt]
# line_length = 120
# tab_width = 4
# bracket_spacing = false
# int_types = 'long'
# multiline_func_header = 'attributes_first'
# quote_style = 'double'
# number_underscore = 'preserve'
# single_line_statement_blocks = 'preserve'
# variable_override_spacing = true
# wrap_comments = false
# ignore = []

# Additional configurations

# [default.model_checker]
# contracts = { '/path/to/project/src/Contract.sol' = [ 'Contract' ] }
# engine = 'chc'
# timeout = 10000
# targets = [ 'assert' ]

# [default.optimizer_details]
# constantOptimizer = true
# yul = true
# this sets the `yulDetails` of the `optimizer_details` for the `default` profile
# [default.optimizer_details.yulDetails]
# stackAllocation = true
# optimizerSteps = 'gTVnfClhnfncITgcraonvcgMtjmCumgUmdgdxVeiOlvdOvarhngxiUaxVhOdjTTDODDdUMrTthUVrrnhrjsvcjVuDmletlOThul'
