[profile.default]
allow_paths = ['interfaces', 'contracts', 'src']
auto_detect_solc = true
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 1
block_timestamp = 1
broadcast = 'broadcast'
bytecode_hash = 'none'
cache = true
cache_path = 'cache'
evm_version = 'london'

# includes the contract's metadata in the contract's json artifact
extra_output = []
# emits the output selection as separate json artifact files
extra_output_files = ['metadata']

ffi = false
force = false
fuzz_max_global_rejects = 65_536
fuzz_max_local_rejects = 16_384
fuzz_runs = 512

# This is an Option, so we can determine in fork mode whether to use the config's gas price
# (if set by user) or the remote client's gas price Option<u64>
gas_price = 10
gas_limit = 9223372036854775807
block_base_fee_per_gas = 0
gas_reports = ['*']

# Ignored Error codes
# 2018 Function state mutability can be restricted to pure
# 3420 Source file does not specify required compiler version
# 3716 Multiple SPDX license identifiers found in source file
ignored_error_codes = [
	1878,
	2018,
	3420,
  3716,
]

initial_balance = '0xffffffffffffffffffffffff'
libraries = []
libs = [
	'lib',
	'node_modules',
]
memory_limit = 33554432
names = false
no_storage_caching = false
offline = false
out = 'out'

remappings = [
	'@openzeppelin/=node_modules/@openzeppelin/',
	'@uniswap/=node_modules/@uniswap/',
	'ds-test/=lib/forge-std/lib/ds-test/src/',
	'forge-std/=lib/forge-std/src/',
]
script = 'script'
sender = '0xafFEaFFEAFfeAfFEAffeaFfEAfFEaffeafFeAFfE'
sizes = false
sparse_mode = false
build_info = false
src = 'contracts'
test = 'contracts/test'
tx_origin = '0xAaaaAaAAaaaAAaAAaAaaaaAAAAAaAaaaAaAaaAA0'
verbosity = 2
# optimizer settings
via_ir = true
# revert_strings = "verboseDebug"
revert_strings = "debug"
optimizer = true
optimizer_runs = 1_337
optimizerSteps = ''

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[profile.ci]
optimizer = false
fuzz_runs = 4069
force = true
verbosity = 4

#[fmt]
#line_length = 80
#tab_width = 4
#bracket_spacing = false

# [default.model_checker]
# contracts = { '/path/to/project/src/Contract.sol' = [ 'Contract' ] }
# engine = 'chc'
# timeout = 10000
# targets = [ 'assert' ]

# [default.optimizer_details]
# constantOptimizer = true
# yul = true
# this sets the `yulDetails` of the `optimizer_details` for the `default` profile
# [default.optimizer_details.yulDetails]
# stackAllocation = true
# optimizerSteps = 'gTVnfClhnfncITgcraonvcgMtjmCumgUmdgdxVeiOlvdOvarhngxiUaxVhOdjTTDODDdUMrTthUVrrnhrjsvcjVuDmletlOThul'
